## You should change each of the following fields
## to customize your blog

title: Stat 386 Blog
description: "This description of the blog will appear on the 'About' page." 
author: Your name
author_description: "This description of who you are will appear on the 'About' page." 

url: https://esnt.github.io ## change this to https://yourusername.github.io
baseurl: /another-stat386-theme ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  ## required
    twitter: 
    facebook: 
    email: 
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




